-- ============================================================
-- TrustTY HRMS - Script tạo cấu trúc cơ sở dữ liệu (DDL)
-- Chỉ chứa lệnh tạo bảng, KHÔNG chứa dữ liệu mẫu.
-- Dữ liệu mẫu được quản lý riêng tại: database/seed-data.js
-- Để seed dữ liệu, chạy: node database/seed.js
-- ============================================================

CREATE DATABASE IF NOT EXISTS QuanLyNhanSu CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE QuanLyNhanSu;

-- 1. Bảng PHONG_BAN
CREATE TABLE IF NOT EXISTS PhongBan (
  MaPB    VARCHAR(10)   NOT NULL,
  TenPB   VARCHAR(100)  NOT NULL,
  MoTa    TEXT,
  CONSTRAINT PK_PHONGBAN PRIMARY KEY (MaPB)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Bảng DU_AN
CREATE TABLE IF NOT EXISTS DuAn (
  MaDA          VARCHAR(20)    NOT NULL,
  TenDA         VARCHAR(100)   NOT NULL,
  MoTa          TEXT,
  TrangThai     VARCHAR(50),
  NgayBD        DATE,
  NgayKT        DATE,
  ChiPhiDuKien  DECIMAL(15,2),
  ChiPhiThucTe  DECIMAL(15,2),
  CONSTRAINT PK_DUAN PRIMARY KEY (MaDA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Bảng CHUC_VU
CREATE TABLE IF NOT EXISTS ChucVu (
  MaCV    VARCHAR(10)   NOT NULL,
  TenCV   VARCHAR(100)  NOT NULL,
  CapBac  INT,
  CONSTRAINT PK_CHUCVU PRIMARY KEY (MaCV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Bảng NHAN_VIEN
CREATE TABLE IF NOT EXISTS NhanVien (
  MaNV          VARCHAR(20)   NOT NULL,
  TenNV         VARCHAR(100)  NOT NULL,
  NgaySinh      DATE,
  DiaChi        VARCHAR(255),
  SoCCCD        VARCHAR(12)   UNIQUE,
  Email         VARCHAR(100)  UNIQUE,
  SDT           VARCHAR(15),
  TrangThai     VARCHAR(50)   DEFAULT 'Đang làm',
  SoTaiKhoanNH  VARCHAR(20),
  MaPB          VARCHAR(10),
  MaCV          VARCHAR(10),
  CONSTRAINT PK_NHANVIEN PRIMARY KEY (MaNV),
  CONSTRAINT FK_NV_PHONGBAN FOREIGN KEY (MaPB) REFERENCES PhongBan(MaPB) ON DELETE SET NULL,
  CONSTRAINT FK_NV_CHUCVU   FOREIGN KEY (MaCV) REFERENCES ChucVu(MaCV)   ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Bảng TAI_KHOAN
CREATE TABLE IF NOT EXISTS TaiKhoan (
  TenTaiKhoan  VARCHAR(50)   NOT NULL,
  MatKhau      VARCHAR(255)  NOT NULL,
  PhanQuyen    VARCHAR(50)   NOT NULL,
  MaNV         VARCHAR(20),
  CONSTRAINT PK_TAIKHOAN PRIMARY KEY (TenTaiKhoan),
  CONSTRAINT FK_TK_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Bảng HOP_DONG
CREATE TABLE IF NOT EXISTS HopDong (
  SoHD    VARCHAR(50)   NOT NULL,
  MaNV    VARCHAR(20),
  LoaiHD  VARCHAR(100),
  NgayKy  DATE          NOT NULL,
  NgayHH  DATE,
  CONSTRAINT PK_HOPDONG PRIMARY KEY (SoHD),
  CONSTRAINT FK_HD_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. Bảng TRINH_DO
CREATE TABLE IF NOT EXISTS TrinhDo (
  MaTD          INT           NOT NULL AUTO_INCREMENT,
  MaNV          VARCHAR(20),
  TenBangCap    VARCHAR(100)  NOT NULL,
  ChuyenNganh   VARCHAR(100),
  NoiDaoTao     VARCHAR(150),
  NamHoanThanh  INT,
  CONSTRAINT PK_TRINHDO PRIMARY KEY (MaTD),
  CONSTRAINT FK_TD_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. Bảng BAO_HIEM
CREATE TABLE IF NOT EXISTS BaoHiem (
  MaBH        VARCHAR(20)   NOT NULL,
  MaNV        VARCHAR(20),
  TenBH       VARCHAR(100)  NOT NULL,
  NgayHetHan  DATE,
  CONSTRAINT PK_BAOHIEM PRIMARY KEY (MaBH),
  CONSTRAINT FK_BH_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. Bảng PHAN_CONG
CREATE TABLE IF NOT EXISTS PhanCong (
  MaNV        VARCHAR(20)  NOT NULL,
  MaDA        VARCHAR(20)  NOT NULL,
  VaiTro      VARCHAR(50),
  ThoiGianTG  DATE,
  CONSTRAINT PK_PHANCONG PRIMARY KEY (MaNV, MaDA),
  CONSTRAINT FK_PC_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE,
  CONSTRAINT FK_PC_DUAN     FOREIGN KEY (MaDA) REFERENCES DuAn(MaDA)     ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. Bảng CHAM_CONG
CREATE TABLE IF NOT EXISTS ChamCong (
  MaCC      INT           NOT NULL AUTO_INCREMENT,
  MaNV      VARCHAR(20),
  Ngay      DATE          NOT NULL,
  GioVao    TIME,
  GioRa     TIME,
  SoGioLam  FLOAT,
  CONSTRAINT PK_CHAMCONG PRIMARY KEY (MaCC),
  CONSTRAINT FK_CC_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. Bảng NGHI_PHEP
CREATE TABLE IF NOT EXISTS NghiPhep (
  MaDon      INT           NOT NULL AUTO_INCREMENT,
  MaNV       VARCHAR(20),
  NgayBD     DATE          NOT NULL,
  NgayKT     DATE          NOT NULL,
  LyDo       VARCHAR(255),
  TrangThai  VARCHAR(50)   DEFAULT 'Chờ duyệt',
  CONSTRAINT PK_NGHIPHEP PRIMARY KEY (MaDon),
  CONSTRAINT FK_NP_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12. Bảng BANG_LUONG
CREATE TABLE IF NOT EXISTS BangLuong (
  MaBL      VARCHAR(20)    NOT NULL,
  MaNV      VARCHAR(20),
  Thang     INT            NOT NULL,
  Nam       INT            NOT NULL,
  LuongCB   DECIMAL(15,2)  NOT NULL,
  PhuCap    DECIMAL(15,2)  DEFAULT 0,
  ThueTNCN  DECIMAL(15,2)  DEFAULT 0,
  ThucLinh  DECIMAL(15,2)  NOT NULL,
  CONSTRAINT PK_BANGLUONG PRIMARY KEY (MaBL),
  CONSTRAINT FK_BL_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 13. Bảng BIEN_DONG_LUONG
CREATE TABLE IF NOT EXISTS BienDongLuong (
  MaBD           INT           NOT NULL AUTO_INCREMENT,
  MaNV           VARCHAR(20),
  HinhThuc       VARCHAR(100),
  NoiDung        VARCHAR(255),
  GiaTien        DECIMAL(15,2),
  NgayQuyetDinh  DATE,
  CONSTRAINT PK_BIENDONGLUONG PRIMARY KEY (MaBD),
  CONSTRAINT FK_BDL_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
